-- 球队词典表
CREATE TABLE IF NOT EXISTS soccer_teams (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name_en VARCHAR(200) NOT NULL UNIQUE,
  name_zh VARCHAR(200) DEFAULT NULL,
  league VARCHAR(120) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_league (league),
  KEY idx_name_zh (name_zh)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 联赛词典表
CREATE TABLE IF NOT EXISTS soccer_leagues (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name_en VARCHAR(200) NOT NULL UNIQUE,
  name_zh VARCHAR(200) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_name_zh (name_zh)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
